// vue/src/components/order/DamageCountSelector.vue
<script setup>
const props = defineProps({
  count: { type: Number, default: 0 },
  label: String
})
const emit = defineEmits(['update:count'])
function decrement() {
  emit('update:count', Math.max(0, props.count - 1))
}
function increment() {
  emit('update:count', props.count + 1)
}
</script>

<template>
  <div class="dcs-container">
    <label class="oi-label">{{ props.label }}</label>
    <div class="dcs-control">
      <button
        type="button"
        class="dcs-btn"
        @click="decrement"
        :disabled="props.count <= 0"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
      <span class="dcs-value">{{ props.count }}</span>
      <button type="button" class="dcs-btn" @click="increment">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="12" y1="5" x2="12" y2="19" />
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
</style>

// src/components/order/DamageCountSelector.jsx
import React from 'react';

function MinusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

function PlusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

export default function DamageCountSelector({ count, onChange }) {
  const decrement = () => onChange(Math.max(0, count - 1));
  const increment = () => onChange(count + 1);

  return (
    <div className="dcs-container">
      <label className="oi-label">Antal skador</label>
      <div className="dcs-control">
        <button
          type="button"
          className="dcs-btn"
          onClick={decrement}
          disabled={count <= 0}
        >
          <MinusIcon className="icon-lg" />
        </button>
        <span className="dcs-value">{count}</span>
        <button type="button" className="dcs-btn" onClick={increment}>
          <PlusIcon className="icon-lg" />
        </button>
      </div>
    </div>
  );
}
