// vue/src/components/order/ProductTypeSelector.vue
<script setup>
import config from '../../setup/config.js'
import { localize } from '../../setup/i18n.js'
import CustomSelect from './ui/CustomSelect.vue'

const props = defineProps({
  productType: String,
  error: String,
  texts: Object
})
const emit = defineEmits(['update'])
const OPTIONS = config.productCategories.map(cat => ({ value: cat.id, label: localize(cat.name) }))
</script>

<template>
  <div class="pts-container">
    <label class="pts-label">{{ props.texts.selectTypeOfProduct }} <span class="text-red">*</span></label>
    <CustomSelect :model-value="props.productType" @update:model-value="val => emit('update', val)" :placeholder="props.texts.select" :options="OPTIONS" :error="!!props.error" />
    <p v-if="props.error" class="pts-error">{{ props.error }}</p>
  </div>
</template>

<style scoped>
</style>

// src/components/order/ProductTypeSelector.jsx
import React from 'react';
import config from '../../config.js';
import t, { localize } from '../../i18n.js';
import CustomSelect from './ui/CustomSelect.jsx';

const OPTIONS = config.productCategories.map((cat) => ({
  value: cat.id,
  label: localize(cat.name),
}));

export default function ProductTypeSelector({ productType, onTypeChange, onOpenChange, error }) {
  const handleChange = (value) => {
    onTypeChange && onTypeChange(value);
    onOpenChange && onOpenChange(false);
  };

  return (
    <div className="pts-container">
      <label className="pts-label">
        {t('firstStep.selectTypeOfProduct')} <span className="text-red">*</span>
      </label>
      <CustomSelect
        value={productType || ''}
        onValueChange={handleChange}
        placeholder={t('firstStep.select')}
        options={OPTIONS}
        error={!!error}
      />
      {error && <p className="pts-error">{error}</p>}
    </div>
  );
}
