// vue/src/components/order/ProductQuantitySelector.vue
<script setup>
import t from '../../setup/i18n.js'

const props = defineProps({
  quantity: { type: Number, default: 0 }
})

const emit = defineEmits(['increase', 'decrease'])

const MAX_QUANTITY = 20

const decrease = () => {
  if (props.quantity > 0) emit('decrease')
}

const increase = () => {
  if (props.quantity < MAX_QUANTITY) emit('increase')
}
</script>

<template>
  <div class="pqs-container">
    <div class="pqs-row">
      <label for="quantity" class="font-medium">
        {{ t('firstStep.selectNumberOfProducts') }} <span class="text-red">*</span>
      </label>
    </div>
    <div class="pqs-control">
      <button
        type="button"
        class="pqs-btn"
        @click="decrease"
        :disabled="props.quantity <= 0"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
      <span class="pqs-value">{{ props.quantity }}</span>
      <button
        type="button"
        class="pqs-btn"
        @click="increase"
        :disabled="props.quantity >= MAX_QUANTITY"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="12" y1="5" x2="12" y2="19" />
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
</style>

// src/components/order/ProductQuantitySelector.jsx
import React from 'react';
import t from '../../i18n.js';

function MinusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

function PlusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

const MAX_QUANTITY = 20;

export default function ProductQuantitySelector({ quantity, onIncrease, onDecrease }) {
  const decrease = () => {
    if (quantity > 0) onDecrease();
  };
  const increase = () => {
    if (quantity < MAX_QUANTITY) onIncrease();
  };
  return (
    <div className="pqs-container">
      <div className="pqs-row">
        <label htmlFor="quantity" className="font-medium">
          {t('firstStep.selectNumberOfProducts')} <span className="text-red">*</span>
        </label>
      </div>
      <div className="pqs-control">
        <button type="button" className="pqs-btn" onClick={decrease} disabled={quantity <= 0}>
          <MinusIcon className="icon-lg" />
        </button>
        <span className="pqs-value">{quantity}</span>
        <button
          type="button"
          className="pqs-btn"
          onClick={increase}
          disabled={quantity >= MAX_QUANTITY}
        >
          <PlusIcon className="icon-lg" />
        </button>
      </div>
    </div>
  );
}
