// vue/src/components/order/ProductQuantitySelector.vue
<script setup>
const props = defineProps({
  quantity: { type: Number, default: 0 },
  texts: { type: Object, default: () => ({}) }
})
const emit = defineEmits(['increase', 'decrease'])

const MAX_QUANTITY = 20

function decrease() {
  if (props.quantity > 0) emit('decrease')
}

function increase() {
  if (props.quantity < MAX_QUANTITY) emit('increase')
}
</script>

<template>
  <div class="pqs-container">
    <div class="pqs-row">
      <label class="font-medium">
        {{ props.texts.selectNumberOfProducts }} <span class="text-red">*</span>
      </label>
    </div>
    <div class="pqs-control">
      <button
        type="button"
        class="pqs-btn"
        @click="decrease"
        :disabled="props.quantity <= 0"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
      <span class="pqs-value">{{ props.quantity }}</span>
      <button
        type="button"
        class="pqs-btn"
        @click="increase"
        :disabled="props.quantity >= MAX_QUANTITY"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="12" y1="5" x2="12" y2="19" />
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
</style>

// .mvp/components/order/ProductQuantitySelector.jsx
import React from 'react';

function MinusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

function PlusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

const MAX_QUANTITY = 20;

export default function ProductQuantitySelector({ quantity, onIncrease, onDecrease }) {
  const decrease = () => {
    if (quantity > 1) onDecrease();
  };
  const increase = () => {
    if (quantity < MAX_QUANTITY) onIncrease();
  };
  return (
    <div className="space-y-2">
      <div className="flex justify-between items-center">
        <label htmlFor="quantity" className="font-medium">
          Hur många produkter gäller det? <span className="text-red-500">*</span>
        </label>
      </div>
      <div className="flex items-center justify-between w-full max-w-md h-14 rounded-lg border border-input overflow-hidden bg-white">
        <button type="button" className="flex items-center justify-center h-full px-6 cursor-pointer text-gray-500 hover:bg-gray-50" onClick={decrease} disabled={quantity <= 1}>
          <MinusIcon className="h-5 w-5" />
        </button>
        <span className="text-xl font-medium flex-1 text-center">{quantity}</span>
        <button
          type="button"
          className="flex items-center justify-center h-full px-6 cursor-pointer text-gray-500 hover:bg-gray-50"
          onClick={increase}
          disabled={quantity >= MAX_QUANTITY}
        >
          <PlusIcon className="h-5 w-5" />
        </button>
      </div>
    </div>
  );
}
