// vue/src/components/order/ui/Badge.vue
<script setup>
const props = defineProps({
  variant: { type: String, default: 'default' }
})
</script>

<template>
  <span :class="['inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium',
                 variant === 'secondary' ? 'bg-gray-100 text-gray-800 border border-gray-300'
                 : variant === 'destructive' ? 'bg-red-100 text-red-800'
                 : variant === 'outline' ? 'border border-gray-300 bg-transparent text-gray-600'
                 : 'bg-gray-100 text-gray-800']">
    <slot />
  </span>
</template>

<style scoped>
/* styling from ui.css */
</style>

// src/ui/Badge.jsx
import React from 'react';

const VARIANTS = {
  default: 'border-transparent bg-primary text-primary-foreground hover:bg-primary/80',
  secondary: 'border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80',
  destructive: 'border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80',
  outline: 'text-foreground',
};

export default function Badge({ variant = 'default', className = '', ...props }) {
  const classes = [
    'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
    VARIANTS[variant] || '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return <div className={classes} {...props} />;
}
