// .mvp/components/order/damage-marker/GarmentDamageMarker.jsx
import React, { useEffect, useState } from 'react';
import InstructionMessage from './InstructionMessage';
import WholeProductList from './WholeProductList';
import MarkerButtons from './MarkerButtons';
import GarmentView from './GarmentView';

export default function GarmentDamageMarker({
  product,
  damageIndex,
  defectId,
  updateDamageDetail,
  updateDefectDetail,
  selectedDamageIndex,
  selectedDefectId,
}) {
  const [damagePositions, setDamagePositions] = useState({});
  const [defectPositions, setDefectPositions] = useState({});
  const [orderMap, setOrderMap] = useState({});
  const [nextOrder, setNextOrder] = useState(1);

  useEffect(() => {
    const dPos = {};
    const dfPos = {};
    const orders = {};
    let maxOrder = 0;
    product.damages.forEach((_, idx) => {
      const detail = product.damageDetails?.[`damage-${idx}`];
      if (detail && detail.position) {
        dPos[idx] = detail.position;
        if (detail.orderIndex) {
          orders[`damage-${idx}`] = detail.orderIndex;
          maxOrder = Math.max(maxOrder, detail.orderIndex);
        }
      }
    });
    if (product.defectDetails) {
      Object.entries(product.otherIssues).forEach(([id, active]) => {
        if (active && product.defectDetails[id]?.position) {
          dfPos[id] = product.defectDetails[id].position;
          const oi = product.defectDetails[id].orderIndex || 0;
          if (oi) {
            orders[id] = oi;
            maxOrder = Math.max(maxOrder, oi);
          }
        }
      });
    }
    setDamagePositions(dPos);
    setDefectPositions(dfPos);
    setOrderMap(orders);
    setNextOrder(maxOrder + 1);
  }, [product]);

  const nextSelection = () => {
    if (damageIndex !== undefined) return { type: 'damage', id: damageIndex };
    if (defectId) return { type: 'defect', id: defectId };
    for (let i = 0; i < product.damages.length; i++) if (!damagePositions[i]) return { type: 'damage', id: i };
    const defects = Object.entries(product.otherIssues).filter(([id, on]) => on).map(([id]) => id);
    for (const id of defects) if (!defectPositions[id]) return { type: 'defect', id };
    return null;
  };

  const handleMark = (x, y, view) => {
    if (damageIndex !== undefined) {
      const pos = { x, y, view };
      setDamagePositions((p) => ({ ...p, [damageIndex]: pos }));
      const orderKey = `damage-${damageIndex}`;
      if (!orderMap[orderKey]) {
        setOrderMap((m) => ({ ...m, [orderKey]: nextOrder }));
        setNextOrder((o) => o + 1);
      }
      updateDamageDetail && updateDamageDetail(damageIndex, { position: pos, orderIndex: orderMap[orderKey] || nextOrder });
      return;
    }
    if (defectId) {
      const pos = { x, y, view };
      setDefectPositions((p) => ({ ...p, [defectId]: pos }));
      if (!orderMap[defectId]) {
        setOrderMap((m) => ({ ...m, [defectId]: nextOrder }));
        setNextOrder((o) => o + 1);
      }
      updateDefectDetail && updateDefectDetail(defectId, { position: pos, orderIndex: orderMap[defectId] || nextOrder });
      return;
    }
  };

  const markWholeProduct = () => {
    handleMark(0.5, 0.5, 'whole');
  };

  const resetAll = () => {
    setDamagePositions({});
    setDefectPositions({});
    setOrderMap({});
    setNextOrder(1);
  };

  const isWholeMarker = (pos) => pos && pos.view === 'whole';

  const imageUrl = product.images ? product.images.front : null;

  const isMarked = damageIndex !== undefined ? !!damagePositions[damageIndex] : defectId ? !!defectPositions[defectId] : false;
  const singleMode = damageIndex !== undefined || !!defectId;
  const totalMarks = Object.keys(damagePositions).length + Object.keys(defectPositions).length;

  return (
    <div className="mt-3 space-y-3">
      <InstructionMessage productType={product.type} isMarked={isMarked} isSingleMarkMode={singleMode} />
      <div className="flex flex-col gap-2">
        <WholeProductList
          product={product}
          damagePositions={damagePositions}
          defectPositions={defectPositions}
          isWholeProductMarker={isWholeMarker}
          removeMarker={(e, idx) => {
            e.stopPropagation();
            setDamagePositions((p) => {
              const { [idx]: removed, ...rest } = p;
              return rest;
            });
          }}
          removeDefectMarker={(e, id) => {
            e.stopPropagation();
            setDefectPositions((p) => {
              const { [id]: removed, ...rest } = p;
              return rest;
            });
          }}
          getDefectLabel={(id) => product.defectLabels?.[id] || id}
          markerSelectionOrder={orderMap}
        />
        <MarkerButtons
          isMarked={isMarked}
          onMarkWholeProduct={markWholeProduct}
          onResetAllMarkers={resetAll}
          isSingleMarkMode={singleMode}
        />
      </div>
      <GarmentView
        productType={product.type}
        imageUrl={imageUrl}
        onMarkPosition={handleMark}
        disabled={false}
        maxMarks={product.damages.length}
        currentMarks={totalMarks}
        selectedForMarking={selectedDamageIndex !== undefined || selectedDefectId !== undefined}
        damagePositions={damagePositions}
        defectPositions={defectPositions}
        productDamages={product.damages}
        defectLabels={product.defectLabels || {}}
        onMarkerDrag={() => {}}
        markerSelectionOrder={orderMap}
      />
    </div>
  );
}

// vue/src/components/order/damage-marker/GarmentDamageMarker.vue
<script setup>
import { ref, watch, computed } from 'vue'
import InstructionMessage from './InstructionMessage.vue'
import MarkerList from './MarkerList.vue'
import MarkerButtons from './MarkerButton.vue'
import GarmentView from './GarmentView.vue'
import { getDefectLabel, getDamageLabel } from '../../../setup/i18n.js'

const props = defineProps({
  product: Object,
  damageIndex: Number,
  defectId: String,
  updateDamageDetail: Function,
  updateDefectDetail: Function,
  selectedDamageIndex: Number,
  selectedDefectId: String,
  onSelectDamage: Function,
  onSelectDefect: Function,
  damageMarkable: { type: Object, default: () => ({}) },
  defectMarkable: { type: Object, default: () => ({}) },
  texts: Object
})

const damagePositions = ref({})
const defectPositions = ref({})
const orderMap = ref({})
const nextOrder = ref(1)

watch(() => props.product, (p) => {
  const dPos = {}
  const dfPos = {}
  const orders = {}
  let maxOrder = 0
  p.damages.forEach((_, idx) => {
    const detail = p.damageDetails?.[`damage-${idx}`]
    if(detail && detail.position){
      dPos[idx]=detail.position
      if(detail.orderIndex){
        orders[`damage-${idx}`]=detail.orderIndex
        maxOrder=Math.max(maxOrder, detail.orderIndex)
      }
    }
  })
  if(p.defectDetails){
    Object.entries(p.otherIssues).forEach(([id,on])=>{
      if(on && p.defectDetails[id]?.position){
        dfPos[id]=p.defectDetails[id].position
        const oi = p.defectDetails[id].orderIndex || 0
        if(oi){ orders[id]=oi; maxOrder=Math.max(maxOrder, oi) }
      }
    })
  }
  damagePositions.value=dPos
  defectPositions.value=dfPos
  orderMap.value=orders
  nextOrder.value=maxOrder+1
},{ immediate:true })

function handleMark(x,y,view){
  if(props.damageIndex!==undefined && props.damageMarkable[props.damageIndex]){
    const pos={x,y,view}
    damagePositions.value = { ...damagePositions.value, [props.damageIndex]: pos }
    const orderKey = `damage-${props.damageIndex}`
    if(!orderMap.value[orderKey]){ orderMap.value = { ...orderMap.value, [orderKey]: nextOrder.value }; nextOrder.value++ }
    props.updateDamageDetail && props.updateDamageDetail(props.damageIndex,{ position: pos, orderIndex: orderMap.value[orderKey] })
    return
  }
  if(props.defectId && props.defectMarkable[props.defectId]){
    const pos={x,y,view}
    defectPositions.value = { ...defectPositions.value, [props.defectId]: pos }
    if(!orderMap.value[props.defectId]){ orderMap.value = { ...orderMap.value, [props.defectId]: nextOrder.value }; nextOrder.value++ }
    props.updateDefectDetail && props.updateDefectDetail(props.defectId,{ position: pos, orderIndex: orderMap.value[props.defectId] })
  }
}

function markWholeProduct(){
  handleMark(0.5,0.5,'whole')
}

function resetAll(){
  damagePositions.value={}
  defectPositions.value={}
  orderMap.value={}
  nextOrder.value=1
  props.product.damages.forEach((_,idx)=>{ props.updateDamageDetail && props.updateDamageDetail(idx,{ position: undefined, orderIndex: undefined }) })
  Object.entries(props.product.otherIssues||{}).forEach(([id,on])=>{ if(on) props.updateDefectDetail && props.updateDefectDetail(id,{ position: undefined, orderIndex: undefined }) })
}

function isWholeMarker(pos){ return pos && pos.view==='whole' }
const imageUrl = computed(() => props.product.images ? props.product.images.front : null )
const isMarked = computed(() => props.damageIndex !== undefined ? !!damagePositions.value[props.damageIndex] : props.defectId ? !!defectPositions.value[props.defectId] : false )
const singleMode = computed(() => props.damageIndex !== undefined || !!props.defectId)
const totalMarks = computed(() => Object.keys(damagePositions.value).length + Object.keys(defectPositions.value).length )

function handleMarkerClick(type,id){
  if(type==='damage' && props.onSelectDamage && props.damageMarkable[id]) props.onSelectDamage(id)
  if(type==='defect' && props.onSelectDefect && props.defectMarkable[id]) props.onSelectDefect(id)
}
</script>

<template>
  <div class="gdm-container">
    <h4 class="gdm-title">{{ props.texts.markDamageBelow }}</h4>
    <InstructionMessage :product-type="props.product.type" :is-marked="isMarked" :is-single-mark-mode="singleMode" :texts="props.texts" />
    <div class="gdm-row">
      <MarkerButtons :on-reset-all-markers="resetAll" :texts="props.texts" />
    </div>
    <div class="gdm-white-section">
      <MarkerList
        :product="props.product"
        :damage-positions="damagePositions"
        :defect-positions="defectPositions"
        :is-whole-product-marker="isWholeMarker"
        :damage-markable="props.damageMarkable"
        :defect-markable="props.defectMarkable"
        :get-damage-label="id => props.product.damageLabels?.[id] || getDamageLabel(props.product.type, props.product.damages[id])"
        :get-defect-label="id => props.product.defectLabels?.[id] || getDefectLabel(props.product.type, id)"
        :marker-selection-order="orderMap"
        :on-select-damage="props.onSelectDamage"
        :on-select-defect="props.onSelectDefect"
        :texts="props.texts"
        :selected-damage-index="props.selectedDamageIndex"
        :selected-defect-id="props.selectedDefectId"
        :remove-damage="idx => { delete damagePositions.value[idx]; delete orderMap.value[`damage-${idx}`]; props.updateDamageDetail && props.updateDamageDetail(idx,{ position: undefined, orderIndex: undefined }) }"
        :remove-defect="id => { delete defectPositions.value[id]; delete orderMap.value[id]; props.updateDefectDetail && props.updateDefectDetail(id,{ position: undefined, orderIndex: undefined }) }"
      />
      <GarmentView
        :product-type="props.product.type"
        :image-url="imageUrl"
        :on-mark-position="handleMark"
        :disabled="false"
        :max-marks="props.product.damages.length"
        :current-marks="totalMarks"
        :selected-for-marking="props.selectedDamageIndex !== undefined || props.selectedDefectId !== undefined"
        :damage-positions="damagePositions"
        :defect-positions="defectPositions"
        :product-damages="props.product.damages"
        :damage-labels="props.product.damageLabels || {}"
        :defect-labels="Object.fromEntries(Object.entries(props.product.otherIssues || {}).filter(([id,on])=>on).map(([id]) => [id, props.product.defectLabels?.[id] || getDefectLabel(props.product.type, id)]))"
        :on-marker-click="handleMarkerClick"
        :marker-selection-order="orderMap"
        :product="props.product"
        :remove-damage="(e,idx)=>{ e && e.stopPropagation && e.stopPropagation(); delete damagePositions.value[idx]; delete orderMap.value[`damage-${idx}`]; props.updateDamageDetail && props.updateDamageDetail(idx,{ position: undefined, orderIndex: undefined }) }"
        :remove-defect="(e,id)=>{ e && e.stopPropagation && e.stopPropagation(); delete defectPositions.value[id]; delete orderMap.value[id]; props.updateDefectDetail && props.updateDefectDetail(id,{ position: undefined, orderIndex: undefined }) }"
        :get-damage-label="(idx)=>props.product.damageLabels?.[idx] || getDamageLabel(props.product.type, props.product.damages[idx])"
        :get-defect-label="id => props.product.defectLabels?.[id] || getDefectLabel(props.product.type,id)"
        :is-whole-product-marker="isWholeMarker"
        :texts="props.texts"
      />
    </div>
  </div>
</template>

<style scoped></style>
