// vue/src/components/order/ui/CustomSelect.vue
<script setup>
import { ref, computed, watch, onBeforeUnmount } from 'vue'

const props = defineProps({
  modelValue: [String, Number],
  options: { type: Array, default: () => [] },
  placeholder: { type: String, default: 'Select an option' },
  error: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false }
})

const emit = defineEmits(['update:modelValue'])

const isOpen = ref(false)
const highlightedIndex = ref(-1)
const selectRef = ref(null)
const listRef = ref(null)

const selectedOption = computed(() => props.options.find(opt => opt.value === props.modelValue))

function handleClickOutside(event) {
  if (selectRef.value && !selectRef.value.contains(event.target)) {
    isOpen.value = false
    highlightedIndex.value = -1
  }
}

watch(isOpen, (isCurrentlyOpen) => {
  if (isCurrentlyOpen) {
    document.addEventListener('mousedown', handleClickOutside)
  } else {
    document.removeEventListener('mousedown', handleClickOutside)
  }
})

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleClickOutside)
})

watch(highlightedIndex, (newIndex) => {
    if (isOpen.value && newIndex >= 0 && listRef.value) {
        const highlightedElement = listRef.value.children[newIndex];
        if(highlightedElement) {
            highlightedElement.scrollIntoView({ block: 'nearest' });
        }
    }
});

function onKeyDown(event) {
    if (props.disabled) return;

    switch (event.key) {
      case 'Enter':
      case ' ':
        event.preventDefault();
        if (isOpen.value && highlightedIndex.value >= 0) {
          handleOptionClick(props.options[highlightedIndex.value].value);
        } else {
          isOpen.value = true;
        }
        break;
      case 'ArrowDown':
        event.preventDefault();
        if (!isOpen.value) {
          isOpen.value = true;
        } else {
          highlightedIndex.value = (highlightedIndex.value + 1) % props.options.length;
        }
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (!isOpen.value) {
          isOpen.value = true;
        } else {
          highlightedIndex.value = (highlightedIndex.value - 1 + props.options.length) % props.options.length;
        }
        break;
      case 'Escape':
        isOpen.value = false;
        highlightedIndex.value = -1;
        break;
    }
}

function handleOptionClick(val) {
  emit('update:modelValue', val)
  isOpen.value = false
  highlightedIndex.value = -1
}
</script>

<template>
  <div class="custom-select" ref="selectRef">
    <button
      type="button"
      class="custom-select-trigger"
      :class="{ error: props.error, disabled: props.disabled }"
      @click="!props.disabled && (isOpen = !isOpen)"
      @keydown="onKeyDown"
      :disabled="props.disabled"
      aria-haspopup="listbox"
      :aria-expanded="isOpen"
    >
      <span class="custom-select-value">
        {{ selectedOption ? selectedOption.label : props.placeholder }}
      </span>
      <svg viewBox="0 0 15 15" width="15" height="15" class="custom-select-icon" :class="{ open: isOpen }">
        <path d="m4.93179 5.43179c.20264-.20264.53284-.20264.73548 0L8 7.76521l2.3328-2.33342c.2026-.20264.5328-.20264.7354 0 .2027.20265.2027.53285 0 .7355L8.36833 8.8682c-.20265.2026-.53285.2026-.73549 0L4.93179 6.1673c-.20264-.2026-.20264-.5328 0-.7355Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"/>
      </svg>
    </button>
    <div v-if="isOpen" class="custom-select-content">
      <div class="custom-select-viewport" ref="listRef" role="listbox">
        <div
          v-for="(option, index) in props.options"
          :key="option.value"
          class="custom-select-item"
          :class="{
            highlighted: highlightedIndex === index,
            selected: option.value === props.modelValue
          }"
          @click="handleOptionClick(option.value)"
          @mouseenter="highlightedIndex = index"
          role="option"
          :aria-selected="option.value === props.modelValue"
        >
          {{ option.label }}
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* uses existing CSS from ui.css */
</style>

// react/src/components/order/ui/CustomSelect.jsx
import React, { useState, useRef, useEffect } from 'react';

const ChevronDownIcon = ({ className = '' }) => (
  <svg
    width="15"
    height="15"
    viewBox="0 0 15 15"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
  >
    <path
      d="m4.93179 5.43179c.20264-.20264.53284-.20264.73548 0L8 7.76521l2.3328-2.33342c.2026-.20264.5328-.20264.7354 0 .2027.20265.2027.53285 0 .7355L8.36833 8.8682c-.20265.2026-.53285.2026-.73549 0L4.93179 6.1673c-.20264-.2026-.20264-.5328 0-.7355Z"
      fill="currentColor"
      fillRule="evenodd"
      clipRule="evenodd"
    />
  </svg>
);

export default function CustomSelect({
  value,
  onValueChange,
  placeholder = "Select an option",
  options = [],
  className = "",
  error = false,
  disabled = false,
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const selectRef = useRef(null);
  const listRef = useRef(null);

  const selectedOption = options.find(opt => opt.value === value);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (selectRef.current && !selectRef.current.contains(event.target)) {
        setIsOpen(false);
        setHighlightedIndex(-1);
      }
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }
  }, [isOpen]);

  useEffect(() => {
    if (isOpen && highlightedIndex >= 0 && listRef.current) {
      const highlightedElement = listRef.current.children[highlightedIndex];
      if (highlightedElement) {
        highlightedElement.scrollIntoView({
          block: 'nearest',
        });
      }
    }
  }, [highlightedIndex, isOpen]);

  const handleKeyDown = (event) => {
    if (disabled) return;

    switch (event.key) {
      case 'Enter':
      case ' ':
        event.preventDefault();
        if (isOpen && highlightedIndex >= 0) {
          onValueChange(options[highlightedIndex].value);
          setIsOpen(false);
          setHighlightedIndex(-1);
        } else {
          setIsOpen(true);
        }
        break;
      case 'ArrowDown':
        event.preventDefault();
        if (!isOpen) {
          setIsOpen(true);
        } else {
          setHighlightedIndex(prev =>
            prev < options.length - 1 ? prev + 1 : 0
          );
        }
        break;
      case 'ArrowUp':
        event.preventDefault();
        if (!isOpen) {
          setIsOpen(true);
        } else {
          setHighlightedIndex(prev =>
            prev > 0 ? prev - 1 : options.length - 1
          );
        }
        break;
      case 'Escape':
        setIsOpen(false);
        setHighlightedIndex(-1);
        break;
    }
  };

  const handleOptionClick = (optionValue) => {
    onValueChange(optionValue);
    setIsOpen(false);
    setHighlightedIndex(-1);
  };

  return (
    <div className={`custom-select ${className}`} ref={selectRef}>
      <button
        type="button"
        className={`custom-select-trigger ${error ? 'error' : ''} ${disabled ? 'disabled' : ''}`}
        onClick={() => !disabled && setIsOpen(!isOpen)}
        onKeyDown={handleKeyDown}
        disabled={disabled}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
      >
        <span className="custom-select-value">
          {selectedOption ? selectedOption.label : placeholder}
        </span>
        <ChevronDownIcon className={`custom-select-icon ${isOpen ? 'open' : ''}`} />
      </button>

      {isOpen && (
        <div className="custom-select-content">
          <div
            className="custom-select-viewport"
            ref={listRef}
            role="listbox"
          >
            {options.map((option, index) => (
              <div
                key={option.value}
                className={`custom-select-item ${highlightedIndex === index ? 'highlighted' : ''} ${option.value === value ? 'selected' : ''}`}
                onClick={() => handleOptionClick(option.value)}
                onMouseEnter={() => setHighlightedIndex(index)}
                role="option"
                aria-selected={option.value === value}
              >
                {option.label}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
