// src/components/order/ConfirmationStep.jsx
import React, { useContext, useMemo } from 'react';
import { DialogClose, DialogContext } from './ui/Dialog.jsx';
import { calculateSummary } from './PriceSummary.jsx';
import t from '../../setup/i18n.js';

export default function ConfirmationStep({
  resetForm,
  products = [],
  orderInfo = {},
  discount = 0,
  onPreview,
}) {
  const dialogCtx = useContext(DialogContext);
  
  // Create complete order JSON for API
  const completeOrderData = useMemo(() => {
    const { productTotals, subTotal, total } = calculateSummary(products, discount);
    
    const orderData = {
      // Order information
      orderInfo: {
        customerNumber: orderInfo.customerNumber || '',
        companyName: orderInfo.companyName || '',
        ordererName: orderInfo.ordererName || '',
        phone: orderInfo.phone || '',
        email: orderInfo.email || '',
        billingCompanyName: orderInfo.billingCompanyName || '',
        billingStreet: orderInfo.billingStreet || '',
        billingZipCode: orderInfo.billingZipCode || '',
        billingCity: orderInfo.billingCity || '',
        sameAsBillingAddress: orderInfo.sameAsBillingAddress || false,
        pickupCompanyName: orderInfo.pickupCompanyName || '',
        pickupStreet: orderInfo.pickupStreet || '',
        pickupZipCode: orderInfo.pickupZipCode || '',
        pickupCity: orderInfo.pickupCity || '',
        sameAsPickupAddress: orderInfo.usePickupAddressForDelivery !== undefined ? orderInfo.usePickupAddressForDelivery : true,
        usePickupAddressForDelivery: orderInfo.usePickupAddressForDelivery !== undefined ? orderInfo.usePickupAddressForDelivery : true,
        deliveryCompanyName: orderInfo.deliveryCompanyName || '',
        deliveryStreet: orderInfo.deliveryStreet || '',
        deliveryZipCode: orderInfo.deliveryZipCode || '',
        deliveryCity: orderInfo.deliveryCity || ''
      },
      
      // Products with enriched data including items from calculateSummary
      products: productTotals.map(productTotal => {
        const originalProduct = products.find(p => p.id === productTotal.id) || {};
        return {
          id: productTotal.id,
          type: productTotal.type,
          employee: originalProduct.employeeName || originalProduct.employee || '',
          employeeName: originalProduct.employeeName || originalProduct.employee || '',
          employeeDepartment: originalProduct.employeeDepartment || originalProduct.department || '',
          artikelNumber: originalProduct.artikelNumber || originalProduct.articleNumber || '',
          lagningsId: originalProduct.lagningsId || originalProduct.repairId || '',
          isEmployeeOwned: originalProduct.isEmployeeOwned || false,
          damages: originalProduct.damages || [],
          defects: originalProduct.defects || [],
          damageDetails: originalProduct.damageDetails || {},
          otherIssues: originalProduct.otherIssues || {},
          images: originalProduct.images || null,
          items: productTotal.items || [],
          subtotal: productTotal.subtotal || 0
        };
      }),
      
      // Summary
      summary: {
        productTotals,
        subTotal,
        discount,
        discountAmount: Math.round(subTotal * (discount / 100)),
        total
      },
      
      // Metadata
      metadata: {
        timestamp: new Date().toISOString(),
        language: 'sv' // Default to Swedish
      }
    };
    
    console.log('Complete Order Data for API:', orderData);
    
    return orderData;
  }, [products, orderInfo, discount]);
  
  const handlePreview = () => {
    onPreview && onPreview(completeOrderData);
  };
  return (
    <div className="confirm-container">
      <div className="confirm-header">
        <h2 className="confirm-title">{t('fourthStep.thankYouTitle')}</h2>
        <DialogClose className="confirm-close" />
      </div>
      <p className="confirm-text">
        {t('fourthStep.orderReceivedMsg')}
      </p>
      {discount > 0 && (
        <p className="confirm-discount">{t('fourthStep.discountMsg').replace('{discount}', discount)}</p>
      )}
      <p className="confirm-steps-intro">{t('fourthStep.instructionsTitle')}</p>
      <ol className="confirm-list">
        <li>{t('fourthStep.step1')}</li>
        <li>{t('fourthStep.step2')}</li>
        <li>{t('fourthStep.step3')}</li>
        <li>{t('fourthStep.step4')}</li>
        <li>{t('fourthStep.step5')}</li>
        <li>{t('fourthStep.step6')}</li>
      </ol>
      <div className="confirm-actions">
        <button
          type="button"
          onClick={resetForm}
          className="secondary-button"
        >
          {t('fourthStep.additionalOrder')}
        </button>
        <button
          type="button"
          onClick={handlePreview}
          className="secondary-button"
        >
          {t('fourthStep.previewEmail')}
        </button>
        <button
          type="button"
          onClick={() => dialogCtx?.onOpenChange(false)}
          className="primary-button"
        >
          {t('fourthStep.close')}
        </button>
      </div>
    </div>
  );
}

// vue/src/components/order/ConfirmationStep.vue
<template>
  <div class="confirm-container">
    <div class="confirm-header">
      <h2 class="confirm-title">{{ texts.thankYouTitle }}</h2>
      <DialogClose class="confirm-close" />
    </div>
    <p class="confirm-text">{{ texts.orderReceivedMsg }}</p>
    <p v-if="discount > 0" class="confirm-discount">{{ texts.discountMsg }}</p>
    <p class="confirm-steps-intro">{{ texts.instructionsTitle }}</p>
    <ol class="confirm-list">
      <li>{{ texts.step1 }}</li>
      <li>{{ texts.step2 }}</li>
      <li>{{ texts.step3 }}</li>
      <li>{{ texts.step4 }}</li>
      <li>{{ texts.step5 }}</li>
      <li>{{ texts.step6 }}</li>
    </ol>
    <div class="confirm-actions">
      <button type="button" class="secondary-button" @click="emit('reset')">
        {{ texts.additionalOrder }}
      </button>
      <button type="button" class="secondary-button" @click="emit('preview', completeOrderData)">
        {{ texts.previewEmail }}
      </button>
      <button type="button" class="primary-button" @click="handleClose">
        {{ texts.close }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { computed, inject } from 'vue'
import { DialogClose } from '../Dialog.vue'
import { calculateSummary } from './PriceSummary.vue'

const props = defineProps({
  products: { type: Array, default: () => [] },
  orderInfo: { type: Object, default: () => ({}) },
  discount: { type: Number, default: 0 },
  texts: { type: Object, default: () => ({}) }
})

const emit = defineEmits(['reset', 'preview', 'close'])
const closeDialog = inject('closeDialog')

function handleClose() {
  closeDialog && closeDialog()
  emit('close')
}

const completeOrderData = computed(() => {
  const { productTotals, subTotal, total } = calculateSummary(props.products, props.discount)
  const orderData = {
    orderInfo: {
      customerNumber: props.orderInfo.customerNumber || '',
      companyName: props.orderInfo.companyName || '',
      ordererName: props.orderInfo.ordererName || '',
      phone: props.orderInfo.phone || '',
      email: props.orderInfo.email || '',
      billingCompanyName: props.orderInfo.billingCompanyName || '',
      billingStreet: props.orderInfo.billingStreet || '',
      billingZipCode: props.orderInfo.billingZipCode || '',
      billingCity: props.orderInfo.billingCity || '',
      sameAsBillingAddress: props.orderInfo.sameAsBillingAddress || false,
      pickupCompanyName: props.orderInfo.pickupCompanyName || '',
      pickupStreet: props.orderInfo.pickupStreet || '',
      pickupZipCode: props.orderInfo.pickupZipCode || '',
      pickupCity: props.orderInfo.pickupCity || '',
      sameAsPickupAddress:
        props.orderInfo.usePickupAddressForDelivery !== undefined
          ? props.orderInfo.usePickupAddressForDelivery
          : true,
      usePickupAddressForDelivery:
        props.orderInfo.usePickupAddressForDelivery !== undefined
          ? props.orderInfo.usePickupAddressForDelivery
          : true,
      deliveryCompanyName: props.orderInfo.deliveryCompanyName || '',
      deliveryStreet: props.orderInfo.deliveryStreet || '',
      deliveryZipCode: props.orderInfo.deliveryZipCode || '',
      deliveryCity: props.orderInfo.deliveryCity || ''
    },
    products: productTotals.map(pt => {
      const orig = props.products.find(p => p.id === pt.id) || {}
      return {
        id: pt.id,
        type: pt.type,
        employee: orig.employeeName || orig.employee || '',
        employeeName: orig.employeeName || orig.employee || '',
        employeeDepartment: orig.employeeDepartment || orig.department || '',
        artikelNumber: orig.artikelNumber || orig.articleNumber || '',
        lagningsId: orig.lagningsId || orig.repairId || '',
        isEmployeeOwned: orig.isEmployeeOwned || false,
        damages: orig.damages || [],
        defects: orig.defects || [],
        damageDetails: orig.damageDetails || {},
        otherIssues: orig.otherIssues || {},
        images: orig.images || null,
        capturedMarkedAreas: orig.capturedMarkedAreas || {},
        items: pt.items || [],
        subtotal: pt.subtotal || 0
      }
    }),
    summary: {
      productTotals,
      subTotal,
      discount: props.discount,
      discountAmount: Math.round(subTotal * (props.discount / 100)),
      total
    },
    metadata: {
      timestamp: new Date().toISOString(),
      language: 'sv'
    }
  }
  console.log('Complete Order Data for API:', orderData)
  return orderData
})
</script>

<style scoped>
</style>
