// .mvp/components/order/DamageCountSelector.jsx
import React from 'react';

function MinusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

function PlusIcon({className}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

export default function DamageCountSelector({ count, onChange }) {
  const decrement = () => onChange(Math.max(0, count - 1));
  const increment = () => onChange(count + 1);

  return (
    <div className="space-y-2">
      <label className="font-medium">Antal skador</label>
      <div className="flex items-center justify-between w-full max-w-xs h-14 rounded-lg border border-input overflow-hidden bg-white">
        <button type="button" className="flex items-center justify-center h-full px-6 cursor-pointer text-gray-500 hover:bg-gray-50" onClick={decrement} disabled={count <= 0}>
          <MinusIcon className="h-5 w-5" />
        </button>
        <span className="text-xl font-medium flex-1 text-center">{count}</span>
        <button type="button" className="flex items-center justify-center h-full px-6 cursor-pointer text-gray-500 hover:bg-gray-50" onClick={increment}>
          <PlusIcon className="h-5 w-5" />
        </button>
      </div>
    </div>
  );
}

// vue/src/components/order/DamageCountSelector.vue
<script setup>
const props = defineProps({
  count: { type: Number, default: 0 },
  label: String
})
const emit = defineEmits(['update:count'])
function decrement() {
  emit('update:count', Math.max(0, props.count - 1))
}
function increment() {
  emit('update:count', props.count + 1)
}
</script>

<template>
  <div class="dcs-container">
    <label class="oi-label">{{ props.label }}</label>
    <div class="dcs-control">
      <button
        type="button"
        class="dcs-btn"
        @click="decrement"
        :disabled="props.count <= 0"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
      <span class="dcs-value">{{ props.count }}</span>
      <button type="button" class="dcs-btn" @click="increment">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-lg">
          <line x1="12" y1="5" x2="12" y2="19" />
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
</style>
