// src/components/order/DamageSelector.jsx
import React from 'react';
import CustomSelect from '../ui/CustomSelect.jsx';

export default function DamageSelector({
  index = 0,
  damage = '',
  option = '',
  damageOptions = [],
  optionOptions = [],
  onDamageChange,
  onOptionChange,
  damageError = null,
  optionError = null,
}) {
  const handleDamageChange = (value) => {
    onDamageChange && onDamageChange(value);
  };

  const handleOptionChange = (value) => {
    onOptionChange && onOptionChange(value);
  };

  const damageSelectOptions = damageOptions.map(opt => ({
    value: opt.id,
    label: opt.label
  }));

  const optionSelectOptions = optionOptions.map(opt => ({
    value: opt.id,
    label: opt.label
  }));

  return (
    <div className="damage-selector">
      <div className="damage-selector-inner">
        <div>
          <div className="damage-label-row">
            <label className="damage-label">
              Skada {index + 1} <span className="text-red">*</span>
            </label>
          </div>
          <CustomSelect
            value={damage}
            onValueChange={handleDamageChange}
            placeholder="Välj typ av skada"
            options={damageSelectOptions}
            error={!!damageError}
          />
          {damageError && <p className="damage-error">{damageError}</p>}
        </div>
        {optionOptions.length > 0 && (
          <div>
            <label className="damage-label">
              Alternativ <span className="text-red">*</span>
            </label>
            <CustomSelect
              value={option}
              onValueChange={handleOptionChange}
              placeholder="Välj"
              options={optionSelectOptions}
              error={!!optionError}
            />
            {optionError && <p className="damage-error">{optionError}</p>}
          </div>
        )}
      </div>
    </div>
  );
}

// vue/src/components/order/DamageSelector.vue
<script setup>
import { computed } from 'vue'
import CustomSelect from './ui/CustomSelect.vue'
import t from '../../setup/i18n.js'

const props = defineProps({
  index: { type: Number, default: 0 },
  damage: { type: String, default: '' },
  option: { type: String, default: '' },
  damageOptions: { type: Array, default: () => [] },
  optionOptions: { type: Array, default: () => [] },
  damageError: { type: String, default: null },
  optionError: { type: String, default: null }
})

const emit = defineEmits(['update:damage', 'update:option'])

const handleDamageChange = (value) => {
  emit('update:damage', value)
}

const handleOptionChange = (value) => {
  emit('update:option', value)
}

const damageSelectOptions = computed(() => props.damageOptions.map(opt => ({
  value: opt.id,
  label: opt.label
})))

const optionSelectOptions = computed(() => props.optionOptions.map(opt => ({
  value: opt.id,
  label: opt.label
})))
</script>

<template>
  <div class="damage-selector">
    <div class="damage-selector-inner">
      <div>
        <div class="damage-label-row">
          <label class="damage-label">
            {{ t('secondStep.damage') }} {{ props.index + 1 }} <span class="text-red">*</span>
          </label>
        </div>
        <CustomSelect
          :model-value="props.damage"
          @update:model-value="handleDamageChange"
          :placeholder="t('secondStep.typeOfDamage')"
          :options="damageSelectOptions"
          :error="!!props.damageError"
        />
        <p v-if="props.damageError" class="damage-error">{{ props.damageError }}</p>
      </div>
      <div v-if="props.optionOptions.length > 0">
        <label class="damage-label">
          {{ t('firstStep.select') }} <span class="text-red">*</span>
        </label>
        <CustomSelect
          :model-value="props.option"
          @update:model-value="handleOptionChange"
          :placeholder="t('firstStep.select')"
          :options="optionSelectOptions"
          :error="!!props.optionError"
        />
        <p v-if="props.optionError" class="damage-error">{{ props.optionError }}</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
</style>
