// src/components/order/DefectsSection.jsx
import React from 'react';

export default function DefectsSection({
  productId,
  issues = [],
  selected = {},
  onToggle,
  error = null,
}) {
  const handleToggle = (issueId) => {
    onToggle && onToggle(productId, issueId);
  };

  return (
    <div>
      <div className="defects-header">
        <h4 className="defects-title">Andra fel och defekter</h4>
      </div>
      <div className={error ? 'defects-wrapper error' : 'defects-wrapper'}>
        <div className="defects-list">
          {issues.map((issue) => (
            <div key={issue.id} className="defect-item">
              <input
                id={`issue-${productId}-${issue.id}`}
                type="checkbox"
                checked={!!selected[issue.id]}
                onChange={() => handleToggle(issue.id)}
              />
              <label htmlFor={`issue-${productId}-${issue.id}`} className="defect-label">
                {issue.label}
              </label>
            </div>
          ))}
        </div>
      </div>
      {error && <p className="defect-error">{error}</p>}
    </div>
  );
}

// vue/src/components/order/DefectsSection.vue
<script setup>
import t from '../../setup/i18n.js'

const props = defineProps({
  productId: [String, Number],
  issues: { type: Array, default: () => [] },
  selected: { type: Object, default: () => ({}) },
  error: { type: String, default: null }
})

const emit = defineEmits(['toggle'])

const handleToggle = (issueId) => {
  emit('toggle', props.productId, issueId)
}
</script>

<template>
  <div>
    <div class="defects-header">
      <h4 class="defects-title">{{ t('secondStep.otherErrorsAndDefects') }}</h4>
    </div>
    <div :class="props.error ? 'defects-wrapper error' : 'defects-wrapper'">
      <div class="defects-list">
        <div v-for="issue in props.issues" :key="issue.id" class="defect-item">
          <input 
            :id="`issue-${props.productId}-${issue.id}`" 
            type="checkbox" 
            :checked="!!props.selected[issue.id]" 
            @change="handleToggle(issue.id)"
          />
          <label :for="`issue-${props.productId}-${issue.id}`" class="defect-label">
            {{ issue.label }}
          </label>
        </div>
      </div>
    </div>
    <p v-if="props.error" class="defect-error">{{ props.error }}</p>
  </div>
</template>

<style scoped>
</style>
