// src/components/order/ProductSelectionStep.jsx
import React from 'react';
import ProductQuantitySelector from './ProductQuantitySelector';
import ProductCard from './ProductCard';
import PriceSummary, { calculateSummary } from './PriceSummary';
import { DialogClose } from '../ui/Dialog.jsx';
import t from '../../i18n.js';

export default function ProductSelectionStep({
  products,
  setProducts,
  quantity,
  setQuantity,
  nextStep,
}) {

  const MAX_QUANTITY = 20;

  const addProduct = () => {
    if (quantity < MAX_QUANTITY) {
      setQuantity(quantity + 1);
      const newProducts = [
        ...products,
        {
          id: quantity + 1,
          type: '',
          damageCount: 0,
          damages: [],
          damageDetails: {},
          damageLabels: {},
          otherIssues: {},
          defectDetails: {},
          defectLabels: {},
          images: null,
          isEmployeeOwned: false,
          employeeName: '',
          employeeDepartment: '',
          damageErrors: {},
          damageOptionErrors: {},
          markerError: undefined,
        },
      ];
      setProducts(newProducts);
    }
  };

  const removeProduct = () => {
    if (quantity > 0) {
      setQuantity(quantity - 1);
      const newProducts = products.slice(0, -1);
      setProducts(newProducts);
    }
  };

  const updateProduct = (id, field, value) => {
    setProducts(prev =>
      prev.map(p => (p.id === id ? { ...p, [field]: value } : p))
    );
  };

  const { total } = calculateSummary(products);

  return (
    <div className="product-selection-step">
      <div className="ps-top">
        <div className="ps-header">
          <h2 className="ps-title">
            {t('firstStep.title')}
          </h2>
          <DialogClose className="close-btn" />
        </div>
        <p>{t('firstStep.instruction')}</p>
        <p className="ps-reminder">{t('firstStep.reminder')}</p>
        <ProductQuantitySelector
          quantity={quantity}
          onIncrease={addProduct}
          onDecrease={removeProduct}
        />
      </div>
      {products.map(p => (
        <ProductCard key={p.id} product={p} onUpdate={updateProduct} />
      ))}
      {products.some(p => p.type) && total > 0 && (
        <div className="summary-card">
          <h3 className="summary-title">{t('firstStep.summary')}</h3>
          <PriceSummary products={products} />
        </div>
      )}
      <button
        type="button"
        onClick={nextStep}
        className="primary-button"
      >
        {t('firstStep.next')}
      </button>
    </div>
  );
}

// vue/src/components/order/ProductSelectionStep.vue
<script setup>
import ProductQuantitySelector from './ProductQuantitySelector.vue'
import ProductCard from './ProductCard.vue'
import PriceSummary from './PriceSummary.vue'
import { calculateSummary } from './priceSummaryUtils.js'
import { DialogClose } from '../Dialog.vue'
import { computed } from 'vue'
import t from '../../setup/i18n.js'

const props = defineProps({
  products: { type: Array, default: () => [] },
  quantity: { type: Number, default: 0 }
})

const emit = defineEmits(['update:products', 'update:quantity', 'next-step'])

const MAX_QUANTITY = 20

const addProduct = () => {
  if (props.quantity < MAX_QUANTITY) {
    emit('update:quantity', props.quantity + 1)
    const newProducts = [
      ...props.products,
      {
        id: props.quantity + 1,
        type: '',
        damageCount: 0,
        damages: [],
        damageDetails: {},
        damageLabels: {},
        otherIssues: {},
        defectDetails: {},
        defectLabels: {},
        images: null,
        isEmployeeOwned: false,
        employeeName: '',
        employeeDepartment: '',
        damageErrors: {},
        damageOptionErrors: {},
        markerError: undefined,
      },
    ]
    emit('update:products', newProducts)
  }
}

const removeProduct = () => {
  if (props.quantity > 0) {
    emit('update:quantity', props.quantity - 1)
    const newProducts = props.products.slice(0, -1)
    emit('update:products', newProducts)
  }
}

const updateProduct = (id, field, value) => {
  const updated = props.products.map(p => 
    p.id === id ? { ...p, [field]: value } : p
  )
  emit('update:products', updated)
}

const summary = computed(() => calculateSummary(props.products))
const total = computed(() => summary.value.total)
</script>

<template>
  <div class="product-selection-step">
    <div class="ps-top">
      <div class="ps-header">
        <h2 class="ps-title">
          {{ t('firstStep.title') }}
        </h2>
        <DialogClose class="close-btn" />
      </div>
      <p>{{ t('firstStep.instruction') }}</p>
      <p class="ps-reminder">{{ t('firstStep.reminder') }}</p>
      <ProductQuantitySelector
        :quantity="props.quantity"
        @increase="addProduct"
        @decrease="removeProduct"
      />
    </div>
    <ProductCard 
      v-for="p in props.products" 
      :key="p.id" 
      :product="p" 
      @update="updateProduct" 
    />
    <div v-if="props.products.some(p => p.type) && total > 0" class="summary-card">
      <h3 class="summary-title">{{ t('firstStep.summary') }}</h3>
      <PriceSummary :products="props.products" />
    </div>
    <button
      type="button"
      @click="emit('next-step')"
      class="primary-button"
    >
      {{ t('firstStep.next') }}
    </button>
  </div>
</template>

<style scoped>
</style>
