// vue/src/components/Banner.vue
<script setup>
import { ref, computed, watch } from 'vue'
import Dialog, { DialogContent, DialogTitle, DialogDescription, DialogClose } from './Dialog.vue'
import OrderForm from './OrderForm.vue'
import { setLanguage, getCurrentLanguage } from '../setup/i18n.js'
import t from '../setup/i18n.js'

const DEMO_CUSTOMER = {
  customerNumber: 'CUS12345',
  companyName: 'Demo AB',
  ordererName: 'Anna Andersson',
  phone: '070-123 45 67',
  email: 'piotr.porzuczek@lyreco.com',
  billingCompanyName: 'Demo AB',
  billingStreet: 'Storgatan 1',
  billingZipCode: '12345',
  billingCity: 'Stockholm',
  pickupCompanyName: 'Demo AB',
  pickupStreet: 'Storgatan 1',
  pickupZipCode: '12345',
  pickupCity: 'Stockholm',
  usePickupAddressForDelivery: true,
  deliveryCompanyName: '',
  deliveryStreet: '',
  deliveryZipCode: '',
  deliveryCity: '',
}

function usePrefilledCustomerData() {
  const prefilledData = ref(null)
  const loadCustomerData = () => { prefilledData.value = DEMO_CUSTOMER }
  const clearPrefilledData = () => { prefilledData.value = null }
  return { prefilledData, loadCustomerData, clearPrefilledData }
}

const props = defineProps({
  prefilledData: { type: Object, default: null },
  isOpen: { type: Boolean, default: undefined },
  onOpenChange: { type: Function, default: undefined }
})

const openInternal = ref(false)
const currentLanguage = ref(getCurrentLanguage())
const forceUpdate = ref(0)
const isPrefillChecked = ref(false)
const email = ref('')
const { prefilledData: internalPrefilledData, loadCustomerData, clearPrefilledData } = usePrefilledCustomerData()

const open = computed(() => props.isOpen !== undefined ? props.isOpen : openInternal.value)

// Use external prefilled data if provided, otherwise use internal
const activePrefilledData = computed(() => 
  props.prefilledData || (isPrefillChecked.value ? internalPrefilledData.value : null)
)

// Include banner email in the data passed to OrderForm
const finalPrefilledData = computed(() => {
  if (activePrefilledData.value) {
    return { ...activePrefilledData.value, email: email.value || activePrefilledData.value.email }
  }
  return email.value ? { email: email.value } : null
})

const formContainerRef = ref(null)

const handleStartClick = () => {
  if (props.isOpen === undefined) openInternal.value = true
  if (props.onOpenChange) props.onOpenChange(true)
}

const handleChange = (value) => {
  if (props.isOpen === undefined) openInternal.value = value
  if (props.onOpenChange) props.onOpenChange(value)
}

const handleLanguageChange = (language) => {
  setLanguage(language)
  currentLanguage.value = language
  forceUpdate.value = forceUpdate.value + 1 // Force re-render to update all text
}

const handlePrefillToggle = (checked) => {
  isPrefillChecked.value = checked
  if (checked) {
    loadCustomerData()
    // Also prefill the banner email from demo customer data
    if (DEMO_CUSTOMER.email) {
      email.value = DEMO_CUSTOMER.email
    }
  } else {
    clearPrefilledData()
    email.value = ''
  }
}

const handleClearData = () => {
  isPrefillChecked.value = false
  email.value = ''
  clearPrefilledData()
}

const languages = [
  { code: 'se', label: 'SE' },
  { code: 'en', label: 'EN' },
  { code: 'no', label: 'NO' }
]
</script>

<template>
  <div class="banner-wrapper">
    <div class="banner">
      <div class="banner-content">
        <div class="banner-controls">
          <div class="language-selector">
            <span class="language-label">{{ t('trigger.language') }}</span>
            <div class="language-options">
              <button
                v-for="lang in languages"
                :key="lang.code"
                class="language-option"
                :class="{ active: currentLanguage === lang.code }"
                @click.stop="handleLanguageChange(lang.code)"
              >
                {{ lang.label }}
              </button>
            </div>
          </div>
          
          <div class="app-controls-section">
            <div class="control-group">
              <label class="checkbox-label">
                <input 
                  type="checkbox" 
                  :checked="isPrefillChecked"
                  @change="handlePrefillToggle($event.target.checked)"
                />
                {{ t('trigger.prefillCustomer') }}
              </label>
            </div>
            <button class="btn-secondary" @click="handleClearData">
              {{ t('trigger.clearData') }}
            </button>
          </div>
        </div>
        <div class="banner-header">
          <div class="banner-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>
            </svg>
          </div>
          <div>
            <h2 class="banner-title">{{ t('trigger.priamry') }}</h2>
            <p class="banner-text">{{ t('trigger.secondary') }}</p>
          </div>
        </div>
        
        <div class="email-input-section">
          <label class="email-label" for="banner-email">
            {{ t('trigger.emailLabel') }}
          </label>
          <input
            id="banner-email"
            type="email"
            class="email-input"
            v-model="email"
            :placeholder="t('trigger.enterEmail')"
            required
          />
        </div>
        
        <button 
          class="banner-cta" 
          @click="handleStartClick"
          :disabled="!email.trim()"
        >
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M9 12l2 2 4-4"/>
            <circle cx="12" cy="12" r="9"/>
          </svg>
          {{ t('trigger.clickToStart') }}
        </button>
      </div>
    </div>
    
    <Dialog :open="open" @update:open="handleChange">
      <DialogContent class="dialog-content">
        <DialogTitle class="sr-only">{{ t('trigger.priamry') }}</DialogTitle>
        <DialogDescription class="sr-only">
          {{ t('firstStep.instruction') }}
        </DialogDescription>
        <div class="form-container" ref="formContainerRef">
          <OrderForm :prefilled-data="finalPrefilledData" :scroll-ref="formContainerRef" />
        </div>
        <DialogClose class="dialog-close" />
      </DialogContent>
    </Dialog>
  </div>
</template>

<style>
@import '../styles/banner.css';
</style>

// react/src/components/Banner.jsx
import React, { useState, useRef } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from './order/ui/Dialog.jsx';
import '../styles/banner.css';
import OrderForm from './OrderForm';
import t, { setLanguage, getCurrentLanguage } from '../setup/i18n.js';

export const DEMO_CUSTOMER = {
  customerNumber: 'CUS12345',
  companyName: 'Demo AB',
  ordererName: 'Anna Andersson',
  phone: '070-123 45 67',
  email: 'piotr.porzuczek@lyreco.com',
  billingCompanyName: 'Demo AB',
  billingStreet: 'Storgatan 1',
  billingZipCode: '12345',
  billingCity: 'Stockholm',
  pickupCompanyName: 'Demo AB',
  pickupStreet: 'Storgatan 1',
  pickupZipCode: '12345',
  pickupCity: 'Stockholm',
  usePickupAddressForDelivery: true,
  deliveryCompanyName: '',
  deliveryStreet: '',
  deliveryZipCode: '',
  deliveryCity: '',
};

export function usePrefilledCustomerData() {
  const [prefilledData, setPrefilledData] = useState(null);
  const loadCustomerData = () => setPrefilledData(DEMO_CUSTOMER);
  const clearPrefilledData = () => setPrefilledData(null);
  return { prefilledData, loadCustomerData, clearPrefilledData };
}

export default function Banner({ prefilledData = null, isOpen, onOpenChange }) {
  const [openInternal, setOpenInternal] = useState(false);
  const [currentLanguage, setCurrentLanguage] = useState(getCurrentLanguage());
  const [forceUpdate, setForceUpdate] = useState(0);
  const [isPrefillChecked, setIsPrefillChecked] = useState(false);
  const [email, setEmail] = useState('');
  const { prefilledData: internalPrefilledData, loadCustomerData, clearPrefilledData } = usePrefilledCustomerData();
  const open = isOpen !== undefined ? isOpen : openInternal;
  const formContainerRef = useRef(null);
  
  // Use external prefilled data if provided, otherwise use internal
  const activePrefilledData = prefilledData || (isPrefillChecked ? internalPrefilledData : null);
  
  // Include banner email in the data passed to OrderForm
  const finalPrefilledData = activePrefilledData ? 
    { ...activePrefilledData, email: email || activePrefilledData.email } :
    email ? { email } : null;

  const handleStartClick = () => {
    if (isOpen === undefined) setOpenInternal(true);
    onOpenChange && onOpenChange(true);
  };

  const handleChange = (value) => {
    if (isOpen === undefined) setOpenInternal(value);
    onOpenChange && onOpenChange(value);
  };

  const handleLanguageChange = (language) => {
    setLanguage(language);
    setCurrentLanguage(language);
    setForceUpdate(prev => prev + 1); // Force re-render to update all text
  };

  const handlePrefillToggle = (checked) => {
    setIsPrefillChecked(checked);
    if (checked) {
      loadCustomerData();
      // Also prefill the banner email from demo customer data
      if (DEMO_CUSTOMER.email) {
        setEmail(DEMO_CUSTOMER.email);
      }
    } else {
      clearPrefilledData();
      setEmail('');
    }
  };

  const handleClearData = () => {
    setIsPrefillChecked(false);
    setEmail('');
    clearPrefilledData();
  };

  const languages = [
    { code: 'se', label: 'SE' },
    { code: 'en', label: 'EN' },
    { code: 'no', label: 'NO' }
  ];

  return (
    <div className="banner-wrapper">

      
      <div className="banner">
        <div className="banner-content">
          <div className="banner-controls">
            <div className="language-selector">
              <span className="language-label">{t('trigger.language')}</span>
              <div className="language-options">
                {languages.map((lang) => (
                  <button
                    key={lang.code}
                    className={`language-option ${currentLanguage === lang.code ? 'active' : ''}`}
                    onClick={(e) => {
                      e.stopPropagation();
                      handleLanguageChange(lang.code);
                    }}
                  >
                    {lang.label}
                  </button>
                ))}
              </div>
            </div>
            
            <div className="app-controls-section">
              <div className="control-group">
                <label className="checkbox-label">
                  <input 
                    type="checkbox" 
                    checked={isPrefillChecked}
                    onChange={(e) => handlePrefillToggle(e.target.checked)}
                  />
                  {t('trigger.prefillCustomer')}
                </label>
              </div>
              <button className="btn-secondary" onClick={handleClearData}>
                {t('trigger.clearData')}
              </button>
            </div>
          </div>
          <div className="banner-header">
          <div className="banner-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>
            </svg>
          </div>
          <div>
            <h2 className="banner-title">{t('trigger.priamry')}</h2>
            <p className="banner-text">{t('trigger.secondary')}</p>
          </div>
          </div>
          
          <div className="email-input-section">
            <label className="email-label" htmlFor="banner-email">
              {t('trigger.emailLabel')}
            </label>
            <input
              id="banner-email"
              type="email"
              className="email-input"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder={t('trigger.enterEmail')}
              required
            />
          </div>
          
          <button 
            className="banner-cta" 
            onClick={handleStartClick}
            disabled={!email.trim()}
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M9 12l2 2 4-4"/>
              <circle cx="12" cy="12" r="9"/>
            </svg>
            {t('trigger.clickToStart')}
          </button>
        </div>
      </div>
      
      <Dialog open={open} onOpenChange={handleChange}>
        <DialogContent className="dialog-content">
          <DialogTitle className="sr-only">{t('trigger.priamry')}</DialogTitle>
          <DialogDescription className="sr-only">
            {t('firstStep.instruction')}
          </DialogDescription>
          <div className="form-container" ref={formContainerRef}>
            <OrderForm prefilledData={finalPrefilledData} scrollRef={formContainerRef} />
          </div>
          <DialogClose className="dialog-close" />
        </DialogContent>
      </Dialog>
    </div>
  );
}
