// vue/src/components/order/EmployeeOwnershipFields.vue
<script setup>
import t from '../../setup/i18n.js'

const props = defineProps({
  product: Object,
  onFieldBlur: Function,
  touchedFields: { type: Object, default: () => ({}) },
  validationErrors: { type: Array, default: () => [] }
})

const emit = defineEmits(['update'])

const fieldPrefix = `product-${props.product.id}-`

const fieldError = (name) => {
  if (!props.touchedFields[name]) return null
  const err = props.validationErrors.find((e) => e.field === name)
  return err ? err.message : null
}

const update = (field, value) => {
  emit('update', field, value)
}
</script>

<template>
  <div class="employee-section">
    <div class="employee-checkbox-row">
      <input 
        :id="`${fieldPrefix}isEmployeeOwned`" 
        type="checkbox" 
        :checked="props.product.isEmployeeOwned" 
        @change="update('isEmployeeOwned', $event.target.checked)" 
      />
      <label :for="`${fieldPrefix}isEmployeeOwned`" class="employee-label-checkbox">
        {{ t('secondStep.belongsToEmployee') }}
      </label>
    </div>
    <div v-if="props.product.isEmployeeOwned" class="employee-fields">
      <div>
        <label :for="`${fieldPrefix}employeeName`" class="employee-label">
          {{ t('secondStep.employeeName') }}
        </label>
        <input 
          :id="`${fieldPrefix}employeeName`" 
          :value="props.product.employeeName"
          @input="update('employeeName', $event.target.value)"
          @blur="() => props.onFieldBlur && props.onFieldBlur(fieldPrefix + 'employeeName')"
          :required="props.product.isEmployeeOwned"
          :class="`employee-input ${fieldError(fieldPrefix + 'employeeName') ? 'error' : ''}`"
        />
        <p v-if="fieldError(fieldPrefix + 'employeeName')" class="employee-error">
          {{ fieldError(fieldPrefix + 'employeeName') }}
        </p>
      </div>
      <div>
        <label :for="`${fieldPrefix}employeeDepartment`" class="employee-label">
          {{ t('secondStep.department') }}
        </label>
        <input 
          :id="`${fieldPrefix}employeeDepartment`" 
          :value="props.product.employeeDepartment"
          @input="update('employeeDepartment', $event.target.value)"
          @blur="() => props.onFieldBlur && props.onFieldBlur(fieldPrefix + 'employeeDepartment')"
          :required="props.product.isEmployeeOwned"
          :class="`employee-input ${fieldError(fieldPrefix + 'employeeDepartment') ? 'error' : ''}`"
        />
        <p v-if="fieldError(fieldPrefix + 'employeeDepartment')" class="employee-error">
          {{ fieldError(fieldPrefix + 'employeeDepartment') }}
        </p>
      </div>
    </div>
  </div>
</template>

<style scoped>
</style>

// components/order/EmployeeOwnershipFields.jsx
import React from 'react';

export default function EmployeeOwnershipFields({ product, onUpdate, onFieldBlur, touchedFields = {}, validationErrors = [] }) {
  const fieldPrefix = `product-${product.id}-`;

  const fieldError = (name) => {
    if (!touchedFields[name]) return null;
    const err = validationErrors.find((e) => e.field === name);
    return err ? err.message : null;
  };

  return (
    <div className="mt-4 pt-4 border-t border-gray-200">
      <div className="flex items-start space-x-2 mb-4">
        <input
          id={`${fieldPrefix}isEmployeeOwned`}
          type="checkbox"
          checked={product.isEmployeeOwned}
          onChange={(e) => onUpdate('isEmployeeOwned', e.target.checked)}
        />
        <label htmlFor={`${fieldPrefix}isEmployeeOwned`} className="text-sm font-medium leading-none cursor-pointer">
          Plagg tillhör anställd
        </label>
      </div>
      {product.isEmployeeOwned && (
        <div className="ml-6 space-y-4">
          <div>
            <label htmlFor={`${fieldPrefix}employeeName`}>Namn på anställd</label>
            <input
              id={`${fieldPrefix}employeeName`}
              value={product.employeeName}
              onChange={(e) => onUpdate('employeeName', e.target.value)}
              onBlur={() => onFieldBlur && onFieldBlur(fieldPrefix + 'employeeName')}
              className={fieldError(fieldPrefix + 'employeeName') ? 'border-red-500' : ''}
            />
            {fieldError(fieldPrefix + 'employeeName') && (
              <p className="text-sm text-red-500 mt-1">{fieldError(fieldPrefix + 'employeeName')}</p>
            )}
          </div>
          <div>
            <label htmlFor={`${fieldPrefix}employeeDepartment`}>Avdelning</label>
            <input
              id={`${fieldPrefix}employeeDepartment`}
              value={product.employeeDepartment}
              onChange={(e) => onUpdate('employeeDepartment', e.target.value)}
              onBlur={() => onFieldBlur && onFieldBlur(fieldPrefix + 'employeeDepartment')}
              className={fieldError(fieldPrefix + 'employeeDepartment') ? 'border-red-500' : ''}
            />
            {fieldError(fieldPrefix + 'employeeDepartment') && (
              <p className="text-sm text-red-500 mt-1">{fieldError(fieldPrefix + 'employeeDepartment')}</p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
